@startuml
!theme mars

title Usecase for Information system

left to right direction

actor Користувач
actor :SafeEco_Bot:

rectangle Software {

    usecase (Вхід в систему)
    usecase (Перегляд інформації про якість повітря)
    usecase (Спілкування з іншими користувачами)
    usecase (Перегляд інформації про чисті місця на вулиці для співів)
    usecase (Надання рекомендацій щодо заходів для збереження особистої безпеки)

   :SafeEco_Bot: -- (Перегляд інформації про якість повітря)
   (Вхід в систему) .> (Перегляд інформації про якість повітря) : include
   (Надання рекомендацій щодо заходів для збереження особистої безпеки) .> (Перегляд інформації про якість повітря) : include
   (Надання рекомендацій щодо заходів для збереження особистої безпеки) .> (Перегляд інформації про чисті місця на вулиці для співів): include
   Користувач -- (Вхід в систему)
   Користувач -- (Перегляд інформації про якість повітря)
   Користувач -- (Перегляд інформації про чисті місця на вулиці для співів)
   Користувач -- (Надання рекомендацій щодо заходів для збереження особистої безпеки)
   Користувач -- (Спілкування з іншими користувачами)
}

@enduml
